[build]
builder = "NIXPACKS"
buildCommand = """
cd backend && npm install --omit=dev
"""

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/v1/health"
restartPolicyType = "ON_FAILURE"
